config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :client_applications, except: [:new] do
    resources :client_application_partners, only: [:index]
    resources :webhook_deliveries, only: [:index, :show] do
      member do
        post :redeliver
      end
    end
  end

  mount ArtsyAuth::Engine => "/"

  get "/health/ping", to: "health#ping"
  get "/docs", to: "pages#show", id: "docs"

  # Partner API

  get "/v1", to: "pages#show", id: "v1/index"
  get "/v1/playground", to: "playground#index"
  get "/v1/terms", to: "pages#show", id: "v1/terms"
  get "/v1/start", to: "v1/start#show"

  # Public API

  get "/v2", to: "pages#show", id: "v2/index"
  %i[
    applications
    artists
    artworks
    authentication
    bidder_positions
    bidders
    bids
    collection_items
    collections
    docs
    editions
    errors
    fairs
    genes
    http
    images
    links
    markdown
    pagination
    partners
    profiles
    rate_limiting
    sales
    search
    shows
    status
    user_details
    users
  ].each do |page|
    get "/v2/docs/#{page}", to: "pages#show", id: "v2/docs/#{page}"
  end
  get "/v2/playground", to: "playground#index"
  get "/v2/terms", to: "pages#show", id: "v2/terms"

  get "/help", to: "help#show"
end

app/views/shared/_footer.html.haml
%footer
  &copy;
  =Date.today.year
  =link_to 'Artsy', 'https://www.artsy.net', target: '_blank'
  |
  =link_to 'About', 'https://www.artsy.net/about', target: '_blank'
  |
  =link_to 'Open Source', 'https://artsy.github.io/open-source/', target: '_blank'
  |
  =link_to 'Privacy', 'https://artsy.net/privacy', target: '_blank'
  |
  =link_to 'Security', 'https://artsy.net/security', target: '_blank'
  |
  =link_to image_tag('blacktocat-16.png', border: 0), 'https://github.com/artsy/doppler', target: '_blank'
  =link_to image_tag('bird_blue_16.png', boder: 0), 'https://twitter.com/artsyopensource'

app/views/shared/_ga.html.haml
- if Rails.env.development?
  = analytics_init local: true
- else
  = analytics_init

app/views/shared/_head.html.haml
%head
  %title Artsy Developers
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/shared/_header.html.haml
%head
  %title Artsy APIs
  = stylesheet_link_tag 'application', media: 'all'
  = stylesheet_link_tag params[:controller]
  = csrf_meta_tags
  = render 'shared/ga'

app/views/shared/_nav.html.haml
= nav_bar static: :top, brand: "The art world in your app. &#0153;".html_safe, responsive: true do
  = menu_group do
    = menu_item "Home", root_path
    = menu_item "My Apps", client_applications_path
    = menu_item "Blog", 'http://artsy.github.io', target: '_blank'
    = menu_item "API Docs", docs_path
    = menu_item "Help", help_path
  = menu_group pull: :right do
    = menu_item "Public API Terms", v2_terms_path
    -if authenticated?
      = menu_item "Sign Out", '/sign_out'
    -else
      = menu_item "Sign In", '/auth/artsy/new'
= bootstrap_flash

- unless request.path.include?('/v1')
  .alert.alert-warning
    %p
      Please note, we are in the process of retiring the
      = link_to 'public api.', '/v2'
      The public api, as well as its documentation and playground, may be taken down at any time without additional notice.
      This change will not affect integration partners using our
      = link_to 'partner api.', '/v1'
    %br/
    %p
      If you're an Artsy partner gallery, reach out to your Artsy Liaison or contact our Support team for assistance.