config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :client_applications, except: [:new] do
    resources :client_application_partners, only: [:index]
    resources :webhook_deliveries, only: [:index, :show] do
      member do
        post :redeliver
      end
    end
  end

  mount ArtsyAuth::Engine => "/"

  get "/health/ping", to: "health#ping"
  get "/docs", to: "pages#show", id: "docs"

  # Partner API

  get "/v1", to: "pages#show", id: "v1/index"
  get "/v1/playground", to: "playground#index"
  get "/v1/terms", to: "pages#show", id: "v1/terms"
  get "/v1/start", to: "v1/start#show"

  # Public API

  get "/v2", to: "pages#show", id: "v2/index"
  %i[
    applications
    artists
    artworks
    authentication
    bidder_positions
    bidders
    bids
    collection_items
    collections
    docs
    editions
    errors
    fairs
    genes
    http
    images
    links
    markdown
    pagination
    partners
    profiles
    rate_limiting
    sales
    search
    shows
    status
    user_details
    users
  ].each do |page|
    get "/v2/docs/#{page}", to: "pages#show", id: "v2/docs/#{page}"
  end
  get "/v2/playground", to: "playground#index"
  get "/v2/terms", to: "pages#show", id: "v2/terms"

  get "/help", to: "help#show"
end

app/models/client_application.rb
class ClientApplication
  include ActiveModel::Model

  attr_accessor :id, :name, :client_id, :client_secret, :enabled, :published_artworks_access_enabled, :redirect_urls, :created_at, :updated_at, :api_version, :roles

  def persisted?
    !id.nil?
  end
end

app/controllers/client_applications_controller.rb
class ClientApplicationsController < ApplicationController
  include OpenRedirectHelper

  before_action :fetch_client_application, only: %i[show edit destroy update]
  before_action :no_cache!, except: [:index]
  before_action :parse_redirect_uris, only: %i[update]

  def show
  end

  def update
    @client_application._put(**client_application_params.to_h)
    fetch_client_application
    render :show
  end

  def index
    @client_applications = artsy_client.applications
  rescue => e
    @error = e.message
  end

  def destroy
    @client_application._delete
    redirect_to client_applications_path
  end

  private

  def fetch_client_application
    @client_application = artsy_client.application(id: params[:id])
    return if @client_application

    flash[:error] = "Invalid application."
    redirect_to client_applications_path
  end

  def parse_redirect_uris
    return unless client_application_params[:redirect_urls]

    client_application_params[:redirect_urls] = client_application_params[:redirect_urls].split.compact.uniq
  end

  def client_application_params
    @client_application_params ||= params.require(:client_application).permit(:name, :redirect_urls, :redirect_uri)
  end
end

app/views/client_applications/edit.html.haml
%h1 Edit App

= link_to "Back to Apps", client_applications_path, class: 'btn'

- if @client_application.enabled && @client_application.published_artworks_access_enabled
  .alert.alert-success
    This application has access to all published artworks.

= bootstrap_form_for ClientApplication.new(@client_application._attributes.to_h), method: 'PUT' do |f|
  %table.table.table-bordered.table-striped
    %tbody#application
      %tr
        %th.text-right Name
        %td= f.text_field :name, hide_label: true, required: true, value: @client_application.name, placeholder: 'This can be any name that you would recognize.'
      %tr
        %th.text-right API Version
        %td#version= @client_application.api_version
      %tr
        %th.text-right Client Id
        %td#client_id= @client_application.client_id
      %tr
        %th.text-right Client Secret
        %td#client_secret= @client_application.client_secret
      %tr
        %th.text-right Redirect URLs
        %td#redirect_urls= f.text_area :redirect_urls, hide_label: true, rows: 5, value: (@client_application.redirect_urls || []).join("\n"), placeholder: 'The location(s) of your application for OAuth workflow.'
      %tr
        %th.text-right Created
        %td#created_at= DateTime.parse(@client_application.created_at).strftime("%B %d, %Y %H:%M")
      %tr
        %th.text-right Updated
        %td#updated_at= DateTime.parse(@client_application.updated_at).strftime("%B %d, %Y %H:%M")
      %tr
        %th.text-right Enabled
        %td#enabled= @client_application.enabled ? 'Yes' : 'No'
      -if @client_application.roles && @client_application.roles.any?
        %tr
          %th.text-right Roles
          %td#roles= @client_application.roles.join(', ')

  = f.primary 'Save'
  = link_to "Cancel", "javascript:history.back()", class: 'btn btn-default'

app/views/client_applications/index.html.haml
%h1 My Apps

- if !@client_applications

  .alert.alert-danger
    There was an error retrieving applications: #{@error}.

- elsif @client_applications.any?

  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th Name
        %th API Version
        %th Client ID
        %th Created
        %th Enabled
        %th &nbsp;

    %tbody.applications
      - @client_applications.each do |client_application|
        %tr
          %td.name= link_to client_application.name, client_application_path(client_application.id)
          %td.api_version= client_application.api_version
          %td.client_id= client_application.client_id
          %td.created_at= DateTime.parse(client_application.created_at).strftime("%B %d, %Y")
          %td.enabled
            = client_application.enabled ? 'Yes' : 'No'
            -if client_application.enabled && client_application.published_artworks_access_enabled
              + Published Artworks
          %td.actions
            = link_to 'edit', edit_client_application_path(client_application.id), class: 'btn btn-primary'
            // version 1 applications are typically production and are protected in Gravity
            = link_to 'destroy', client_application_path(client_application.id), disabled: client_application.api_version == 1, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'
- else

  .alert.alert-info
    No apps found

app/views/client_applications/show.html.haml
%h1 App

= link_to "Back to Apps", client_applications_path, class: 'btn'

- if @client_application.enabled && @client_application.published_artworks_access_enabled
  .alert.alert-success
    This application has access to all published artworks.

%table.table.table-bordered.table-striped
  %tbody#application
    %tr
      %th.text-right Name
      %td#name= @client_application.name
    %tr
      %th.text-right API Version
      %td#api_version= @client_application.api_version
    %tr
      %th.text-right Client Id
      %td#client_id= @client_application.client_id
    %tr
      %th.text-right Client Secret
      %td#client_secret= @client_application.client_secret
    %tr
      %th.text-right Redirect URLs
      %td#redirect_urls
        -if @client_application.redirect_urls && @client_application.redirect_urls.any?
          %pre= @client_application.redirect_urls.join("\n")
        -else
          None
    %tr
      %th.text-right Created
      %td#created_at= DateTime.parse(@client_application.created_at).strftime("%B %d, %Y %H:%M")
    %tr
      %th.text-right Updated
      %td#updated_at= DateTime.parse(@client_application.updated_at).strftime("%B %d, %Y %H:%M")
    %tr
      %th.text-right Enabled
      %td#enabled= @client_application.enabled ? 'Yes' : 'No'
    -if @client_application.roles && @client_application.roles.any?
      %tr
        %th.text-right Roles
        %td#roles= @client_application.roles.join(', ')
    -if @client_application.api_version == 1
      %tr
        %th.text-right Configured Application Partners
        %td#client_application_partners
          = link_to "Link", client_application_client_application_partners_path(@client_application.id)
      %tr
        %th.text-right Webhook Deliveries
        %td#client_application_partners
          = link_to "Link", client_application_webhook_deliveries_path(@client_application.id)

= link_to 'Edit', edit_client_application_path(@client_application.id), class: 'btn btn-default'
// version 1 applications are typically production and are protected in Gravity
= link_to 'Destroy', client_application_path(@client_application.id), disabled: @client_application.api_version == 1, method: :delete, confirm: "Are you sure?", class: 'btn btn-danger'