config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  resources :client_applications, except: [:new] do
    resources :client_application_partners, only: [:index]
    resources :webhook_deliveries, only: [:index, :show] do
      member do
        post :redeliver
      end
    end
  end

  mount ArtsyAuth::Engine => "/"

  get "/health/ping", to: "health#ping"
  get "/docs", to: "pages#show", id: "docs"

  # Partner API

  get "/v1", to: "pages#show", id: "v1/index"
  get "/v1/playground", to: "playground#index"
  get "/v1/terms", to: "pages#show", id: "v1/terms"
  get "/v1/start", to: "v1/start#show"

  # Public API

  get "/v2", to: "pages#show", id: "v2/index"
  %i[
    applications
    artists
    artworks
    authentication
    bidder_positions
    bidders
    bids
    collection_items
    collections
    docs
    editions
    errors
    fairs
    genes
    http
    images
    links
    markdown
    pagination
    partners
    profiles
    rate_limiting
    sales
    search
    shows
    status
    user_details
    users
  ].each do |page|
    get "/v2/docs/#{page}", to: "pages#show", id: "v2/docs/#{page}"
  end
  get "/v2/playground", to: "playground#index"
  get "/v2/terms", to: "pages#show", id: "v2/terms"

  get "/help", to: "help#show"
end

app/models/webhook_delivery.rb
class WebhookDelivery
  include ActiveModel::Model

  attr_accessor :id, :response_status, :error_class, :created_at, :completed_at, :webhook_event, :webhook_id, :webhook_url

  def initialize(attributes = {})
    super
    if attributes[:webhook_event].present?
      self.webhook_event = WebhookEvent.new(attributes[:webhook_event])
    end
  end
end

app/controllers/webhook_deliveries_controller.rb
class WebhookDeliveriesController < ApplicationController
  include Paginatable
  before_action :set_client_application_id, :set_access_token

  def index
    cache_key = "webhook_deliveries/#{@client_application_id}/page/#{@page}/size/#{@size}"

    # Use Rails.cache to cache the API response across requests
    response = Rails.cache.fetch(cache_key, expires_in: 10.minutes) do
      fetch_webhook_deliveries
    end

    @webhook_deliveries = response[:body].map do |webhook_delivery_data|
      build_webhook_delivery(webhook_delivery_data)
    end

    @total_pages = calculate_total_pages(response[:headers]["X-Total-Count"].to_i, @size)
    @current_page = @page.to_i
  rescue => e
    @error = e.message
  end

  def show
    response = ClientApplicationService.fetch_webhook_delivery(
      @access_token,
      id: params[:id]
    )

    @webhook_delivery = build_webhook_delivery(response[:body])
  rescue => e
    @error = e.message
  end

  def redeliver
    response = ClientApplicationService.redeliver_webhook_delivery(
      @access_token,
      id: params[:id]
    )

    if response[:body][:status] == "success"
      flash[:notice] = "Webhook redelivery initiated successfully."
    else
      flash[:alert] = "Failed to redeliver the webhook event: #{response[:error]}"
    end

    redirect_back(fallback_location: client_application_webhook_delivery_path(params[:client_application_id], params[:id]))
  end

  private

  def build_webhook_delivery(data)
    WebhookDelivery.new(
      id: data[:id],
      response_status: data[:response_status],
      error_class: data[:error_class],
      created_at: data[:created_at],
      completed_at: data[:completed_at],
      webhook_event: data[:webhook_event],
      webhook_id: data[:webhook_id],
      webhook_url: data[:webhook_url]
    )
  end

  def fetch_webhook_deliveries
    response = ClientApplicationService.fetch_webhook_deliveries(
      @access_token,
      client_application_id: @client_application_id,
      page: @page,
      size: @size,
      total_count: true
    )

    {body: response[:body], headers: response[:headers]}
  end

  def set_client_application_id
    @client_application_id = params[:client_application_id]
  end

  def set_access_token
    @access_token = session[:access_token]
  end

  def client_application_partner_params
    params.require(:client_application).permit(:client_application_id)
  end
end

app/views/webhook_deliveries/index.html.haml
%h1 Webhook Deliveries

= link_to "Back to App", client_application_path(params[:client_application_id]), class: 'btn'
- if !@webhook_deliveries.any?
  .alert.alert-warning
    There are no attempted webhook delivery events

- elsif @webhook_deliveries.any?
  %table.table.table-bordered.table-striped
    %thead
      %tr
        %th ID
        %th Event Name
        %th Response Status
        %th Error Class
        %th Created At
        %th Completed At
        %th &nbsp;

    %tbody.applications
      - @webhook_deliveries.each do |webhook_delivery|
        %tr
          %td.id= link_to webhook_delivery.id, client_application_webhook_delivery_path(params[:client_application_id], webhook_delivery.id)
          %td.event_name= webhook_delivery.webhook_event.name
          %td.response_status{ class: status_class(webhook_delivery.response_status) }= webhook_delivery.response_status
          %td.error_class= webhook_delivery.error_class
          %td.created_at= webhook_delivery.created_at && DateTime.parse(webhook_delivery.created_at).strftime("%B %d, %Y")
          %td.completed_at= webhook_delivery.completed_at && DateTime.parse(webhook_delivery.completed_at).strftime("%B %d, %Y")
          %td.actions
            = link_to 'Redeliver', redeliver_client_application_webhook_delivery_path(params[:client_application_id], webhook_delivery.id), method: :post, data: { confirm: "Are you sure?" }, class: 'btn btn-primary'



  = link_to 'Previous', client_application_webhook_deliveries_path(page: @current_page - 1) if @current_page > 1
  = link_to 'Next', client_application_webhook_deliveries_path(page: @current_page + 1) if @current_page < @total_pages

app/views/webhook_deliveries/show.html.haml
%h1 Webhook Delivery Details

= link_to "Back to Webhook List", client_application_webhook_deliveries_path(params[:client_application_id]), class: 'btn'
- if @error.present?
  .alert.alert-warning
    Something went wrong!
- else
  %table.table.table-bordered
    %tr
      %th Event Name
      %td= @webhook_delivery.webhook_event.name

    %tr
      %th Response Status
      %td{ class: status_class(@webhook_delivery.response_status) }= @webhook_delivery.response_status

    %tr
      %th Error Class
      %td= @webhook_delivery.error_class || "None"

    %tr
      %th Created At
      %td= @webhook_delivery.created_at && DateTime.parse(@webhook_delivery.created_at).strftime("%B %d, %Y")

    %tr
      %th Completed At
      %td= @webhook_delivery.completed_at && DateTime.parse(@webhook_delivery.completed_at).strftime("%B %d, %Y")


    %tr
      %th Webhook ID
      %td= @webhook_delivery.webhook_id

    %tr
      %th Configured Webhook Endpoint URL
      %td= @webhook_delivery.webhook_url

    %tr
      %th Redeliver
      %td.actions
        = link_to 'Redeliver', redeliver_client_application_webhook_delivery_path(params[:client_application_id], @webhook_delivery.id), method: :post, data: { confirm: "Are you sure?" }, class: 'btn btn-primary'



  %h2 Webhook Event Payload

  %pre
    %code
      = JSON.pretty_generate(@webhook_delivery.webhook_event.as_json)